
title: My Resume
url: 'http://www.jamesvanaselja.com'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or server.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: James Vanaselja
tagline: Recent IT Grad
pic: 100profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: Vanaselja.James@knights.ucf.edu  
phone: (321) 508-7125
website: www.jamesvanaselja.com
linkedin: james-vanaselja-328861105/
github: jman1118
twitter: '@jvanaselja'


# Tracker
analytics: 
#Update all the sections by editing the files inside _includes folder.
