
title: My Resume
url: 'https://www.jamesvanaselja.com'
enforce_ssl: www.jamesvanaselja.com
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or server.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: James Vanaselja
tagline: Seasoned Help Desk technician seeking to move into Cybersecurity
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: Vanaselja.James@knights.ucf.edu  
phone: (321) 508-7125
website: www.jamesvanaselja.com
linkedin: JamesVanaselja
github: jman1118



# Tracker
analytics: 
#Update all the sections by editing the files inside _includes folder.
